# version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: listing_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend1:
    build: ./backend
    container_name: nest_backend
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: yourpassword
      DATABASE_NAME: task_db
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    command: sh -c "echo 'Frontend built'"

    
volumes:
  postgres_data:
